<div class="zone-items">
    <ul class="level-1">
        <li class="cate no-items home">
            <a class="" href="#" data-permalink="">
                <span class="fa fa-overview"></span>
                <span class="text">Console</span>
            </a>
        </li>
        <li class="cate no-items tenant">
            <a  class=""  href="#" data-permalink="">
                <span class="fa fa-overview"></span>
                <span class="text">Event Source</span>
            </a>
        </li>
        <li class="cate no-items order">
            <a class="" href="#" data-permalink="">
                <span class="fa fa-overview"></span>
                <span class="text">Subscriber</span>
            </a>
        </li>
        <li class="cate no-items template">
            <a class="" href="#" data-permalink="">
                <span class="fa fa-overview"></span>
                <span class="text">Event Log</span>
            </a>
        </li>
    </ul>
</div>
